AllCops:
  Exclude:
    - vendor/**/*
    - Gemfile*
    - '*.gemspec'
  NewCops: enable
  TargetRubyVersion: 2.6

# Gemspec/RequireMFA:
#   Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - spec/**/*
  Max: 50

Metrics/AbcSize:
  Max: 42

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 20

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/StringConcatenation:
  Exclude:
    - spec/**/*

Style/StringLiterals:
  Enabled: false
